version: "3"
services:
  web:
     build: .
     ports:
       - "8000:80"
       - "443:443"
     links:
       - db
     network_mode: "host"
  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Rocklin123
      - MYSQL_DATABASE=database