version: "3"
services:
  web:
     build: .
     ports:
       - "8000:80"
       - "443:443"
     links:
       - db
  db:
    image: "microsoft/mssql-server-linux"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Rocklin123
      - MYSQL_DATABASE=database