version: "3"
services:
    web:
        build: .
        ports:
            - "8000:8000"
        command: bash -c "dotnet ef database --verbose && dotnet run"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        container_name: test01