version: "3"
services:
  web:
     build: .
     ports:
       - "8000:80"
       - "443:443"
     links:
       - db
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Rocklin123"
      ACCEPT_EULA: "Y"