version: "3"
services:
    web:
         build:
            context: .
            dockerfile: web-app/Dockerfile
         ports:
       - 8000:80
         network_mode: "host"
         depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Rocklin123"
            ACCEPT_EULA: "Y"